version: "3"
services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
     - data:/data
     - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  watchtower:
    image: containrrr/watchtower:latest
    restart: unless-stopped
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock 
volumes:
  data:
